// components/MediaModal.tsx
'use client';

import { useEffect, useState, useCallback, useRef } from 'react';
import type { Tag, MediaItemWithTags, ShareLink } from '@/lib/db';

// Re-exported for consumers that imported this type from this module.
export type { MediaItemWithTags as ModalMediaItem };

interface Props {
  item: MediaItemWithTags;
  onClose: () => void;
  onDeleted: () => void;
}

function formatDuration(secs: number): string {
  const h = Math.floor(secs / 3600);
  const m = Math.floor((secs % 3600) / 60);
  const s = Math.floor(secs % 60);
  if (h > 0) return `${h}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`;
  return `${m}:${String(s).padStart(2, '0')}`;
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  if (bytes < 1024 * 1024 * 1024) return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
  return `${(bytes / (1024 * 1024 * 1024)).toFixed(2)} GB`;
}

export default function MediaModal({ item, onClose, onDeleted }: Props) {
  const [descExpanded, setDescExpanded] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const [includeInRandom, setIncludeInRandom] = useState(item.include_in_random === 1);

  // Tag state
  const [tags, setTags] = useState<Tag[]>(item.tags ?? []);
  const [allTags, setAllTags] = useState<Tag[]>([]);
  const [tagInput, setTagInput] = useState('');
  const [tagSuggestions, setTagSuggestions] = useState<Tag[]>([]);
  const tagInputRef = useRef<HTMLInputElement>(null);

  // Share state
  const [shareLinks, setShareLinks] = useState<ShareLink[]>([]);
  const [shareExpanded, setShareExpanded] = useState(false);
  const [shareAllowDownload, setShareAllowDownload] = useState(true);
  const [shareExpiryDays, setShareExpiryDays] = useState('');
  const [shareCreating, setShareCreating] = useState(false);
  const [copiedToken, setCopiedToken] = useState<string | null>(null);

  const fileSrc = `/api/media/${item.id}/file`;
  const thumbnailSrc = item.thumbnail_path ? `/api/media/${item.id}/thumbnail` : null;

  // Close on Escape
  const handleKey = useCallback(
    (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    },
    [onClose]
  );

  useEffect(() => {
    document.addEventListener('keydown', handleKey);
    document.body.style.overflow = 'hidden';
    return () => {
      document.removeEventListener('keydown', handleKey);
      document.body.style.overflow = '';
    };
  }, [handleKey]);

  useEffect(() => {
    fetch('/api/tags')
      .then((r) => r.json())
      .then((data: Tag[]) => setAllTags(data))
      .catch(() => {});
  }, []);

  // Load share defaults from settings and existing share links
  useEffect(() => {
    fetch('/api/settings')
      .then((r) => r.json())
      .then((s) => {
        if (s.share_default_expiry_days !== undefined) setShareExpiryDays(s.share_default_expiry_days);
        if (s.share_default_allow_download !== undefined) setShareAllowDownload(s.share_default_allow_download === '1');
      })
      .catch(() => {});
    fetch(`/api/media/${item.id}/share`)
      .then((r) => r.json())
      .then((data: ShareLink[]) => setShareLinks(data))
      .catch(() => {});
  }, [item.id]);

  async function handleCreateShareLink() {
    setShareCreating(true);
    try {
      let expiresAt: string | null = null;
      if (shareExpiryDays) {
        const d = new Date();
        d.setDate(d.getDate() + parseInt(shareExpiryDays, 10));
        expiresAt = d.toISOString();
      }
      const res = await fetch(`/api/media/${item.id}/share`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ allowDownload: shareAllowDownload, expiresAt }),
      });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const link: ShareLink = await res.json();
      setShareLinks((prev) => [link, ...prev]);
    } catch { /* ignore */ }
    setShareCreating(false);
  }

  async function handleRevokeShareLink(token: string) {
    await fetch(`/api/media/${item.id}/share/${token}`, { method: 'DELETE' }).catch(() => {});
    setShareLinks((prev) => prev.filter((l) => l.token !== token));
  }

  async function copyShareLink(token: string) {
    const url = `${window.location.origin}/share/${token}`;
    await navigator.clipboard.writeText(url).catch(() => {});
    setCopiedToken(token);
    setTimeout(() => setCopiedToken(null), 2000);
  }

  // Filter suggestions as the user types
  useEffect(() => {
    const q = tagInput.trim().toLowerCase();
    if (!q) {
      setTagSuggestions([]);
      return;
    }
    const current = new Set(tags.map((t) => t.name.toLowerCase()));
    setTagSuggestions(
      allTags.filter(
        (t) => t.name.toLowerCase().includes(q) && !current.has(t.name.toLowerCase())
      )
    );
  }, [tagInput, allTags, tags]);

  async function addTag(name: string) {
    const trimmed = name.trim();
    if (!trimmed) return;
    if (tags.some((t) => t.name.toLowerCase() === trimmed.toLowerCase())) {
      setTagInput('');
      return;
    }
    try {
      const res = await fetch(`/api/media/${item.id}/tags`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name: trimmed }),
      });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const tag: Tag = await res.json();
      setTags((prev) => [...prev, tag]);
      setAllTags((prev) => (prev.some((t) => t.id === tag.id) ? prev : [...prev, tag]));
    } catch { /* ignore */ }
    setTagInput('');
    setTagSuggestions([]);
  }

  async function removeTag(tagId: string) {
    const previous = tags;
    const current = tags.filter((t) => t.id !== tagId);
    setTags(current);
    try {
      const res = await fetch(`/api/media/${item.id}/tags`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ tags: current.map((t) => t.name) }),
      });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
    } catch {
      setTags(previous);
    }
  }

  async function handleToggleRandom() {
    const next = !includeInRandom;
    setIncludeInRandom(next);
    try {
      const res = await fetch(`/api/media/${item.id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ includeInRandom: next }),
      });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
    } catch {
      setIncludeInRandom(!next);
    }
  }

  async function handleDelete() {
    if (!confirm('Delete this item and its files from disk?')) return;
    setDeleting(true);
    try {
      await fetch(`/api/media/${item.id}`, { method: 'DELETE' });
      onClose();
      onDeleted();
    } finally {
      setDeleting(false);
    }
  }

  const displayTitle = item.title ?? item.file_path.split('/').pop() ?? item.file_path;
  const desc = item.description ?? '';
  const isLongDesc = desc.length > 300;

  const metadata: { label: string; value: string | null }[] = [
    { label: 'Uploader', value: item.uploader },
    { label: 'Duration', value: item.duration ? formatDuration(item.duration) : null },
    {
      label: 'Resolution',
      value: item.width && item.height ? `${item.width}×${item.height}` : null,
    },
    { label: 'Format', value: item.format ? item.format.toUpperCase() : null },
    { label: 'File size', value: item.file_size ? formatBytes(item.file_size) : null },
    {
      label: 'Added',
      value: new Date(item.created_at).toLocaleString(undefined, {
        dateStyle: 'medium',
        timeStyle: 'short',
      }),
    },
  ].filter((r) => r.value !== null);

  return (
    /* Backdrop */
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4"
      onClick={onClose}
    >
      {/* Modal panel — stop propagation so clicks inside don't close */}
      <div
        className="relative bg-surface-1 border border-border rounded-2xl shadow-2xl w-full max-w-3xl max-h-[92vh] flex flex-col overflow-hidden"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Close button */}
        <button
          onClick={onClose}
          className="absolute top-3 right-3 z-10 text-text-secondary hover:text-text-primary bg-surface-2/80 hover:bg-surface-3 rounded-full w-8 h-8 flex items-center justify-center transition-colors"
          aria-label="Close"
        >
          ✕
        </button>

        {/* Media area */}
        <div className="bg-black flex items-center justify-center" style={{ maxHeight: '60vh' }}>
          {item.type === 'video' ? (
            <video
              src={fileSrc}
              controls
              autoPlay
              poster={thumbnailSrc ?? undefined}
              className="w-full object-contain"
              style={{ maxHeight: '60vh' }}
            />
          ) : (
            // eslint-disable-next-line @next/next/no-img-element
            <img
              src={thumbnailSrc ?? fileSrc}
              alt={displayTitle}
              className="object-contain w-full"
              style={{ maxHeight: '60vh' }}
              onError={(e) => {
                if (thumbnailSrc && e.currentTarget.src !== fileSrc) {
                  e.currentTarget.src = fileSrc;
                }
              }}
            />
          )}
        </div>

        {/* Scrollable info panel */}
        <div className="overflow-y-auto flex flex-col gap-4 p-5">
          {/* Title */}
          <h2 className="text-lg font-semibold text-text-primary leading-snug pr-8">{displayTitle}</h2>

          {/* Source URL */}
          {item.url && (
            <a
              href={item.url}
              target="_blank"
              rel="noopener noreferrer"
              className="text-xs text-accent hover:text-accent-hover truncate transition-colors"
              title={item.url}
            >
              {item.url}
            </a>
          )}

          {/* Description */}
          {desc && (
            <div className="flex flex-col gap-1">
              <p className="text-xs font-medium text-text-muted uppercase tracking-wider">Description</p>
              <p className="text-sm text-text-secondary whitespace-pre-line leading-relaxed">
                {isLongDesc && !descExpanded ? desc.slice(0, 300) + '…' : desc}
              </p>
              {isLongDesc && (
                <button
                  onClick={() => setDescExpanded((v) => !v)}
                  className="self-start text-xs text-text-muted hover:text-text-secondary transition-colors"
                >
                  {descExpanded ? 'Show less' : 'Show more'}
                </button>
              )}
            </div>
          )}

          {/* Tags editor */}
          <div className="flex flex-col gap-2">
            <p className="text-xs font-medium text-text-muted uppercase tracking-wider">Tags</p>

            {/* Current tags */}
            <div className="flex flex-wrap gap-1.5">
              {tags.map((tag) => (
                <span
                  key={tag.id}
                  className="flex items-center gap-1 px-2.5 py-1 rounded-full bg-accent-subtle text-accent text-xs font-medium"
                >
                  {tag.name}
                  <button
                    onClick={() => removeTag(tag.id)}
                    className="text-accent hover:text-text-primary transition-colors leading-none"
                    aria-label={`Remove tag ${tag.name}`}
                  >
                    ×
                  </button>
                </span>
              ))}
              {tags.length === 0 && (
                <span className="text-xs text-text-muted italic">No tags yet</span>
              )}
            </div>

            {/* Add tag input with autocomplete */}
            <div className="relative">
              <div className="flex gap-2">
                <input
                  ref={tagInputRef}
                  type="text"
                  value={tagInput}
                  onChange={(e) => setTagInput(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter') {
                      e.preventDefault();
                      addTag(tagInput);
                    }
                  }}
                  placeholder="Add a tag…"
                  className="flex-1 bg-surface-2 border border-border rounded-lg px-3 py-1.5 text-sm text-text-primary placeholder:text-text-muted focus:outline-none focus:border-border-strong"
                />
                <button
                  onClick={() => addTag(tagInput)}
                  disabled={!tagInput.trim()}
                  className="px-3 py-1.5 bg-surface-2 hover:bg-surface-3 text-text-primary text-sm rounded-lg transition-colors disabled:opacity-40"
                >
                  Add
                </button>
              </div>

              {/* Suggestions dropdown */}
              {tagSuggestions.length > 0 && (
                <div className="absolute top-full left-0 right-0 mt-1 bg-surface-2 border border-border rounded-lg shadow-xl overflow-hidden z-10">
                  {tagSuggestions.slice(0, 8).map((tag) => (
                    <button
                      key={tag.id}
                      onClick={() => addTag(tag.name)}
                      className="w-full text-left px-3 py-2 text-sm text-text-secondary hover:bg-surface-3 hover:text-text-primary transition-colors"
                    >
                      {tag.name}
                    </button>
                  ))}
                </div>
              )}
            </div>
          </div>

          {/* Metadata grid */}
          {metadata.length > 0 && (
            <div className="grid grid-cols-2 gap-x-6 gap-y-2 text-sm">
              {metadata.map(({ label, value }) => (
                <div key={label} className="flex flex-col gap-0.5">
                  <span className="text-xs text-text-muted">{label}</span>
                  <span className="text-text-primary">{value}</span>
                </div>
              ))}
            </div>
          )}

          {/* Include in random toggle */}
          <label className="flex items-center gap-3 cursor-pointer select-none self-start">
            <div
              onClick={handleToggleRandom}
              className={`relative w-9 h-5 rounded-full transition-colors ${includeInRandom ? 'bg-accent' : 'bg-surface-3'}`}
            >
              <div
                className={`absolute top-0.5 left-0.5 w-4 h-4 bg-white rounded-full shadow transition-transform ${includeInRandom ? 'translate-x-4' : 'translate-x-0'}`}
              />
            </div>
            <span className="text-sm text-text-secondary">Include in random</span>
          </label>

          {/* Share section */}
          <div className="flex flex-col gap-2">
            <button
              onClick={() => setShareExpanded((v) => !v)}
              className="flex items-center gap-2 text-xs font-medium text-text-muted uppercase tracking-wider hover:text-text-secondary transition-colors self-start"
            >
              <span>Share</span>
              {shareLinks.length > 0 && (
                <span className="px-1.5 py-0.5 rounded bg-surface-2 text-text-secondary normal-case tracking-normal font-normal">
                  {shareLinks.length}
                </span>
              )}
              <span>{shareExpanded ? '▲' : '▼'}</span>
            </button>

            {shareExpanded && (
              <div className="flex flex-col gap-3 bg-surface-2/50 rounded-xl p-4">
                {/* Create form */}
                <div className="flex flex-col gap-2">
                  <div className="flex flex-wrap gap-3 items-center">
                    <label className="flex items-center gap-2 text-sm text-text-secondary cursor-pointer">
                      <input
                        type="checkbox"
                        checked={shareAllowDownload}
                        onChange={(e) => setShareAllowDownload(e.target.checked)}
                        className="w-3.5 h-3.5 rounded accent-blue-500"
                      />
                      Allow download
                    </label>
                    <select
                      value={shareExpiryDays}
                      onChange={(e) => setShareExpiryDays(e.target.value)}
                      className="bg-surface-2 border border-border rounded-lg px-2 py-1 text-sm text-text-primary focus:outline-none focus:border-border-strong"
                    >
                      <option value="">No expiry</option>
                      <option value="1">1 day</option>
                      <option value="7">7 days</option>
                      <option value="30">30 days</option>
                      <option value="90">90 days</option>
                    </select>
                    <button
                      onClick={handleCreateShareLink}
                      disabled={shareCreating}
                      className="text-sm px-3 py-1.5 bg-accent hover:bg-accent-hover disabled:opacity-50 text-white rounded-lg transition-colors"
                    >
                      {shareCreating ? 'Creating…' : 'Create link'}
                    </button>
                  </div>
                </div>

                {/* Existing links */}
                {shareLinks.length > 0 && (
                  <div className="flex flex-col gap-1.5">
                    {shareLinks.map((link) => (
                      <div
                        key={link.token}
                        className="flex items-center gap-2 text-xs bg-surface-base rounded-lg px-3 py-2"
                      >
                        <span className="text-text-muted font-mono flex-1 truncate min-w-0">
                          /share/{link.token.slice(0, 8)}…
                        </span>
                        <span className="text-text-muted shrink-0">
                          {link.expires_at
                            ? new Date(link.expires_at).toLocaleDateString(undefined, { dateStyle: 'medium' })
                            : 'no expiry'}
                        </span>
                        <span className="text-text-muted shrink-0">
                          {link.allow_download ? '⬇' : ''}
                        </span>
                        <button
                          onClick={() => copyShareLink(link.token)}
                          className="shrink-0 px-2 py-1 bg-surface-2 hover:bg-surface-3 text-text-secondary rounded transition-colors"
                        >
                          {copiedToken === link.token ? 'Copied!' : 'Copy'}
                        </button>
                        <button
                          onClick={() => handleRevokeShareLink(link.token)}
                          className="shrink-0 px-2 py-1 bg-red-900/40 hover:bg-red-800/60 text-red-400 rounded transition-colors"
                        >
                          Revoke
                        </button>
                      </div>
                    ))}
                  </div>
                )}

                {shareLinks.length === 0 && (
                  <p className="text-xs text-text-muted italic">No active share links</p>
                )}
              </div>
            )}
          </div>

          {/* Divider + actions */}
          <div className="border-t border-border pt-3 flex gap-2">
            <a
              href={fileSrc}
              download
              className="flex-1 text-center text-sm bg-surface-2 hover:bg-surface-3 text-text-primary py-2 rounded-lg transition-colors"
            >
              Download
            </a>
            <button
              onClick={handleDelete}
              disabled={deleting}
              className="flex-1 text-sm bg-red-900/40 hover:bg-red-800/60 text-red-400 py-2 rounded-lg transition-colors disabled:opacity-50"
            >
              {deleting ? 'Deleting…' : 'Delete'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

// frontend/src/components/MediaModal.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref, watch } from 'vue'
import { api, type MediaItem, type ShareLink, type Tag } from '@/api'

const props = defineProps<{ item: MediaItem }>()
const emit = defineEmits<{ close: []; deleted: []; updated: [MediaItem] }>()

const tagInput = ref('')
const tags = ref<Tag[]>([...(props.item.tags || [])])
const shares = ref<ShareLink[]>([])
const includeRandom = ref(props.item.include_in_random === 1)
const busy = ref(false)
const copiedToken = ref<string | null>(null)
let copiedTimer: number | undefined

watch(
  () => props.item,
  (v) => {
    tags.value = [...(v.tags || [])]
    includeRandom.value = v.include_in_random === 1
  },
)

onMounted(async () => {
  shares.value = await api(`/api/media/${props.item.id}/share`)
})

onUnmounted(() => {
  if (copiedTimer !== undefined) window.clearTimeout(copiedTimer)
})

async function saveTags() {
  const names = tags.value.map((t) => t.name)
  tags.value = await api(`/api/media/${props.item.id}/tags`, {
    method: 'PUT',
    body: JSON.stringify({ tags: names }),
  })
}

async function addTag() {
  const name = tagInput.value.trim()
  if (!name) return
  const tag = await api<Tag>(`/api/media/${props.item.id}/tags`, {
    method: 'POST',
    body: JSON.stringify({ name }),
  })
  if (!tags.value.find((t) => t.id === tag.id)) tags.value.push(tag)
  tagInput.value = ''
}

async function toggleRandom() {
  const updated = await api<MediaItem>(`/api/media/${props.item.id}`, {
    method: 'PATCH',
    body: JSON.stringify({ includeInRandom: !includeRandom.value }),
  })
  includeRandom.value = updated.include_in_random === 1
  emit('updated', updated)
}

async function copyShareUrl(token: string) {
  try {
    await navigator.clipboard.writeText(shareUrl(token))
    copiedToken.value = token
    if (copiedTimer !== undefined) window.clearTimeout(copiedTimer)
    copiedTimer = window.setTimeout(() => {
      copiedToken.value = null
    }, 1500)
  } catch { /* clipboard may be unavailable */ }
}

async function createShare() {
  const link = await api<ShareLink>(`/api/media/${props.item.id}/share`, {
    method: 'POST',
    body: JSON.stringify({ allowDownload: true }),
  })
  shares.value.unshift(link)
  await copyShareUrl(link.token)
}

async function revokeShare(token: string) {
  await api(`/api/media/${props.item.id}/share/${token}`, { method: 'DELETE' })
  shares.value = shares.value.filter((s) => s.token !== token)
}

async function remove() {
  if (!confirm('Delete this media?')) return
  busy.value = true
  await api(`/api/media/${props.item.id}`, { method: 'DELETE' })
  emit('deleted')
  emit('close')
}

function shareUrl(token: string) {
  return `${location.origin}/share/${token}`
}
</script>

<template>
  <div class="fixed inset-0 z-[60] flex items-center justify-center p-4" @keydown.esc="emit('close')">
    <div class="absolute inset-0 bg-black/70" @click="emit('close')" />
    <div class="relative bg-surface-1 border border-border rounded-2xl max-w-3xl w-full max-h-[90vh] overflow-y-auto shadow-xl">
      <div class="bg-black flex items-center justify-center max-h-[50vh]">
        <video
          v-if="item.type === 'video'"
          :src="`/api/media/${item.id}/file`"
          controls
          class="max-h-[50vh] w-full"
          :poster="item.thumbnail_path ? `/api/media/${item.id}/thumbnail` : undefined"
        />
        <img
          v-else
          :src="`/api/media/${item.id}/file`"
          :alt="item.title || ''"
          class="max-h-[50vh] object-contain"
        />
      </div>
      <div class="p-5 flex flex-col gap-4">
        <div class="flex items-start justify-between gap-3">
          <div>
            <h2 class="text-lg font-semibold text-text-primary">{{ item.title || 'Untitled' }}</h2>
            <p class="text-xs text-text-muted truncate">{{ item.url }}</p>
          </div>
          <button class="text-text-muted hover:text-text-primary" @click="emit('close')">✕</button>
        </div>

        <div class="flex flex-wrap gap-2 items-center">
          <span
            v-for="t in tags"
            :key="t.id"
            class="text-xs px-2 py-1 rounded-full bg-surface-2 text-text-secondary"
          >{{ t.name }}</span>
          <form class="flex gap-1" @submit.prevent="addTag">
            <input v-model="tagInput" class="bg-surface-2 border border-border rounded-lg px-2 py-1 text-xs" placeholder="Add tag" />
            <button class="text-xs px-2 py-1 rounded-lg bg-accent text-white">Add</button>
          </form>
          <button class="text-xs text-text-muted underline" @click="saveTags">Save tags</button>
        </div>

        <label class="flex items-center gap-2 text-sm text-text-secondary">
          <input type="checkbox" :checked="includeRandom" @change="toggleRandom" />
          Include in random
        </label>

        <div class="flex flex-col gap-2">
          <div class="flex items-center justify-between">
            <h3 class="text-sm font-medium">Share links</h3>
            <button class="text-xs px-3 py-1 rounded-lg bg-surface-2 hover:bg-surface-3" @click="createShare">Create</button>
          </div>
          <div v-for="s in shares" :key="s.token" class="flex items-center gap-2 text-xs">
            <a :href="shareUrl(s.token)" class="text-accent truncate flex-1" target="_blank">{{ shareUrl(s.token) }}</a>
            <button
              class="text-text-muted hover:text-text-primary shrink-0"
              @click="copyShareUrl(s.token)"
            >{{ copiedToken === s.token ? 'Copied' : 'Copy' }}</button>
            <button class="text-text-muted hover:text-rose-400" @click="revokeShare(s.token)">Revoke</button>
          </div>
        </div>

        <div class="flex justify-end gap-2 pt-2 border-t border-border">
          <button class="px-3 py-1.5 text-sm rounded-lg text-rose-400 hover:bg-surface-2" :disabled="busy" @click="remove">Delete</button>
        </div>
      </div>
    </div>
  </div>
</template>
